store_management/config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  
  get 'welcome/login'
  get 'welcome/show'
  
  get 'welcome/validate_login'
  post 'welcome/validate_login'
  
  get 'store/' => 'store#index'
  resources :user
  resources :store
  resources :product, :defaults => {:format => "json"}
  

 

end

store_management/app/models/option_type.rb
class OptionType
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, type: String
  
  has_and_belongs_to_many :products
  has_many :option_values
  
end

store_management/app/models/option_value.rb
class OptionValue
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, type: String
  belongs_to :option_type
  belongs_to :variant
end

store_management/app/models/product.rb
class Product
  
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :code, type: String
  field :description, type: String
  
  field :brand, type: String
  field :quantity, type: Float
  
  field :cost, type: Float  # precio del producto del proveedor
  field :pvp, type: Float   # precio del producto que vendo a los clientes
                            # (tengo que ponerlo porque a veces se redondea los valores)
                            
  field :utility, type: Float # el porcentaje de utilidad
  
  has_and_belongs_to_many :option_types
  has_many :variants
  belongs_to :store
end

store_management/app/models/store.rb
class Store
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, type: String
  has_many :products
  has_many :users
end

store_management/app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, type: String
  field :last, type: String
  field :username, type: String
  field :email, type: String
  field :password, type: String
  
  belongs_to :store
  #def deserialize(object)
    #super(object).try(:to_datetime) # Call deserialize in Timekeeping
    #end
end

store_management/app/models/variant.rb
class Variant
  include Mongoid::Document
  include Mongoid::Timestamps
  
  
  belongs_to :product
  has_many :option_values
end

store_management/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private 
  # => just is available to controllers and prevent use 
  # => it as an action since is private
  def current_user
    
    #if it is found return
    User.find(session[:user_id]) 
    #catch error thrown ActiveRecord
    #rescue ActiveRecord::RecordNotFound
    user = User.create
    session[:cart_id] = cart.id
    cart
  end
  
end

store_management/app/controllers/product_controller.rb
class ProductController < ApplicationController
  respond_to :json
  
  def index
    action = params[:action]
    @products = Product.limit(90).entries
  end
  
end

store_management/app/controllers/store_controller.rb
class StoreController < ApplicationController
  respond_to :json
  
  def create
  end
  
  def index
    #@products = Product.limit(10).entries
    #respond_with @products
    #puts "\n\n\n\n\nProducts: #{@products.count}\n\n\n\n\n"
  end
  
end

store_management/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  def login
    
  end
  
  def show
    #redirect_to({ action: 'login' }, alert: "Something serious happened")
  end
  
  def validate_login
    user       = User.where(username: "efrainastudillo")
    if user.count > 0 
      #redirect_to "index"
      json = {success: true, msg: "Welcome #{user.first.name}"}
    else
      json = {success: false, msg: "Login failed"}
     
    end
    
    respond_to do |format|
      
      format.html {  redirect_to store_index_path }
    
      format.json do
        render json: json
      end
    end
     
  end
  
end

store_management/app/helpers/application_helper.rb
module ApplicationHelper
  
  def create_sesion
    
  end
end

store_management/app/helpers/product_helper.rb
module ProductHelper
end

store_management/app/helpers/welcome_helper.rb
module WelcomeHelper
end

store_management/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store Management</title>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" />
  <link href='http://fonts.googleapis.com/css?family=Poiret+One|Josefin+Slab|Muli|Architects+Daughter|Raleway:300' rel='stylesheet' type='text/css' />

  <!-- This line enable using polymer components-->
  
  
  <%= csrf_meta_tags %>
</head>
<body>
  
  

              <%= yield %>
              
</body>
</html>

store_management/app/views/layouts/store.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store Management</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href='http://fonts.googleapis.com/css?family=Poiret+One|Josefin+Slab|Muli|Architects+Daughter|Raleway:300' rel='stylesheet' type='text/css'>

  <!-- This line unable using polymer components-->
  
</head>
<body>
<div class="container-fluid">
  <div class="row">
    
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="row" style="background-color: #00B789">
        <div class="col-md-3 col-xs-3 sm-store-logo">
          <p>Mi Ferretería</p>
        </div>
        
        <div class="col-md-9 col-sm-9 col-xs-9 sm-store-header-menu">
          <ul>
            <li>
              <a href="#">
                 <i class="fa fa-power-off fa-1x"></i>
              </a>
            </li>
            <li>
              <a href="#" style="font-size: 12px; padding: 10px">
                <img src="/assets/person1.jpg" alt="Inventory" width="40" height="40" class="img-circle" />
                <span>Juan Macas</span>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fa fa-inbox fa-1x"></i>
                <span class="badge" style="background-color: #D75F49">8</span>
              </a>
            </li>
            <li>
              <a href="#" data-toggle="tooltip" data-placement="right" title="Tooltip on right">
                <i class="fa fa-bell fa-1x"></i>
                <span class="badge" style="background-color: #D75F49">42</span>
              </a>
            </li>
          </ul>
        </div>
        
      </div>
    </div>
    
    
  </div> <!-- end row -->
  
  <div class="row" style="background-color: #003040;">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="row">
        <div class="col-md-1 col-sm-1 col-xs-1">
          <div class="sm-store-menu" data-ng-controller="MenuController">
            <ul>
              <li>
                <a href="#">
                  <span>
                    <span><i class="fa fa-cubes fa-4x"></i></span>
                    <span>Productos</span>
                  </span>
                </a>
                <!-- sub-menu -->
                <ul>
                  <li><span class="title">Acciones Generales {{ data.message }}</span></li>
                  <li><a href="/store/new"><span class="content">Agregar Producto</span></a></li>
                  <li><a href="/store"><span class="content">Mostrar todos los Productos</span></a></li>
                  <li><span class="title">Productos</span></li>
                  <li><a href="" data-ng-click="Show('pvc')">
                    <span class="content">PVC</span></a></li>
                  <li><a href="" data-ng-click="Show('materiales')">
                    <span class="content">Materiales</span></a></li>
                  <li><a href="" data-ng-click="Show('herramientas')">
                    <span class="content">Herramientas</span></a></li>      
                  <li><a href="" data-ng-click="Show('aceros')"><span class="content">Aceros</span></a></li>  
                  <li><a href="" data-ng-click="Show('materialelec')"><span class="content">Material Eléctrico</span></a></li>
                  <li><a href="" data-ng-click="Show('pintura')"><span class="content">Pintura</span></a></li>
                  <li><a href="" data-ng-click="Show('maquinaria')"><span class="content">Maquinaria</span></a></li>
                  <li><a href="" data-ng-click="Show('techos')"><span class="content">Techos</span></a></li>
                  <li><a href="" data-ng-click="Show('fregadero')"><span class="content">Fregadero</span></a></li>
                  <li><a href="" data-ng-click="Show('griferia')"><span class="content">Grifería</span></a></li>
                  <li><a href="" data-ng-click="Show('manguera')"><span class="content">Mangueras</span></a></li>
                  <li><a href="" data-ng-click="Show('cerrajeria')"><span class="content">Cerrajería</span></a></li>
                  <li><a href="" data-ng-click="Show('bondex')"><span class="content">Bondex y Porcelana</span></a></li>
                  <li><a href="" data-ng-click="Show('pvc')"><span class="content">Plásticos</span></a></li>
                  <li><a href="" data-ng-click="Show('pvc')"><span class="content">Espejos</span></a></li>
                  <li><a href="" data-ng-click="Show('pvc')"><span class="content">Piso Flotante</span></a></li>
                  <li><a href="" data-ng-click="Show('pvc')"><span class="content">Bloques y Mat. de Construcción</span></a></li>
                </ul>
                <!-- end sub-menu -->
              </li>
              <li>
                <a href="#">
                  <span>
                    <span><i class="fa fa-money fa-4x"></i></span>
                    <span>Facturación</span>
                  </span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span>
                    <span><i class="fa fa-file-pdf-o fa-4x"></i></span>
                    <span>Reportes</span>
                  </span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span>
                    <i class="fa fa-cogs fa-4x"></i>
                    <span>Configuración</span>
                  </span>
                </a>
              </li>
            </ul>
          </div>
          <!-- end sm-store-menu -->
        </div>
        <div class="col-md-11 col-sm-11 col-xs-11" style="background-color: #EFEFEF">
          <%= yield %>
          
          
          
          
         
          
          <div class="sm-store-content" >
            <div>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a>         is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a></div>
            <span style="text-align: center">Design by Efraín Astudillo</span>
          </div>
          
        </div>
        
      </div>
    </div>
  </div> <!-- end row -->

</div> <!-- end container fluid -->


  <div id="myModal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Modal title</h4>
        </div>
        <div class="modal-body">
          <p>One fine body&hellip;</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->


</body>
</html>

store_management/app/views/store/index.html.erb
<div class="sm-store-content" data-st-table="shownProducts" st-safe-src="products" data-ng-controller="ProductController">
  <div>
    <ol class="breadcrumb">
      <li><a href="#">Todos los Productos</a></li>
      <li><a href="#">{{ data.products }}</a></li>
      <li class="active">Chapas</li>
    </ol>
  </div>
  <div>
    <button id="smNewProduct" type="button" class="btn btn-primary" data-ng-click="AddProduct()">Nuevo Producto</button>
    <form class="form-inline pull-right">
      <div class="form-group has-feedback">
        <input type="text" data-st-search class="form-control" id="inputSuccess4" aria-describedby="inputSuccess4Status">
        <a href="#"><span class="glyphicon glyphicon-search form-control-feedback" aria-hidden="true"></span></a>
        <span id="inputSuccess4Status" class="sr-only">(success)</span>
      </div>
    </form>
  </div>
  <br />
  <table  class="table table-condensed table-hover">
    <thead>
		<tr id='sample'>
			<th st-sort="code">Código</th>
			<th st-sort="description">Descripción</th> 
			<th st-sort="quantity">Cantidad</th>
			<th st-sort="cost">Costo</th>
			<th st-sort="pvp" st-skip-natural="true">PVP</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<tr st-select-row="row" st-select-mode="multiple" class="repeated-item" data-ng-repeat-start="product in shownProducts " data-ng-click="ShowDescriptionProduct( product.code, $event )">
		  <td>{{ product.code }}</td>
		  <td>{{ product.description }}</td>
		  <td>{{ product.quantity }}</td>
		  <td>{{ product.cost | currency}}</td>
		  <td>{{ product.pvp | currency}}</td>

		  <td>
		    <a href="#{{ product.code }}"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a>
		    <a href="#{{ product.code }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
		    <a href="#{{ product.code }}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
		  </td>
		</tr>
		<!-- Show description of the product -->
		<tr class='product-desc' id="{{product.code}}" data-ng-repeat-end> 
		  <td colspan="6"> 
			  <span class='row'>
				  <span class='col-md-3 col-sm-3 col-xs-3'> {{product.quantity}} </span>
				  <span class='col-md-3 col-sm-3 col-xs-3'> {{product.quantity}} </span>
				  <span class='col-md-3 col-sm-3 col-xs-3'> {{product.quantity}} </span>
				  <span class='col-md-3 col-sm-3 col-xs-3'> {{product.quantity}} </span>
			  </span>
		  </td>
		</tr>
	</tbody>
	<tfoot>
		<tr>
			<td colspan="6" class="text-center">
				<div st-pagination="" st-items-by-page="10" st-displayed-pages="8"></div>
			</td>
		</tr>
	</tfoot>
  </table>
  {{ data.products }}
</div>



<!-- end sm-store-content -->
<div class="sm-store-content">
  <p><img src="/assets/inventory.png" alt="Inventory" width="200" height="200" class="img-circle" /></p>
  <h1>Inventario</h1>
</div>

store_management/app/views/store/new.html.erb
<div data-ng-controller="ProductsController">
  <div class="sm-store-content" >
    <div class="row" style="border-bottom: solid 1px; border-color: #DDD; margin-bottom: 20px">
      <div class="col-md-12" style="text-align: center;">
        <h3>Crear Producto</h3>
      </div>
    </div>
    
    <div class="row">
      <form novalidate >
      <div class="col-md-6">
        <div class="form-group">
          <label for="sm-frm-name">Nombre</label>
          <input type="text" class="form-control" id="sm-frm-name" placeholder="Ingrese el nombre del producto">
        </div>
        <div class="form-group">
          <label for="sm-frm-description">Descripción</label>
          <textarea cols="40" rows="5" class="form-control" id="sm-frm-description" 
          placeholder="Ingrese la descripción del producto"> </textarea>
        </div>
      </div>
      <div class="col-md-6">
        
        <div class="form-group">
          <label for="sm-frm-cost">Costo</label>
          <div class="input-group">
            <input type="text" class="form-control" id="sm-frm-cost" 
            placeholder="Ingrese el costo del producto"  aria-describedby="basic-addon1"/>
            <span class="input-group-addon" id="basic-addon1"><i class="fa fa-usd"></i></span>
          </div>
        </div>
        
        <div class="form-group">
          <label for="sm-frm-utility">Utilidad</label>
          <div class="input-group">
            <input type="text" class="form-control" id="sm-frm-utility" 
            placeholder="Ingrese la utilidad del producto en %" aria-describedby="basic-addon2"/>
            <span class="input-group-addon" id="basic-addon2">%</span>
          </div>
        </div>
        
        <div class="form-group">
          <label for="sm-frm-pvp">P.V.P.</label>
          <div class="input-group">
            <input type="text" class="form-control" id="sm-frm-pvp" 
            placeholder="Ingrese el PVP del producto." aria-describedby="basic-addon3"/>
            <span class="input-group-addon" id="basic-addon3"><i class="fa fa-usd"></i></span>
          </div>
        </div>
      
      </div>
    </form>
    </div>
    
  
    

  </div>

  <div class="sm-store-content">
     <form novalidate>
         Name: <input type="text" ng-model="user.name" /><br />
         E-mail: <input type="email" ng-model="user.email" /><br />
         Gender: <input type="radio" ng-model="user.gender" value="male" />male
         <input type="radio" ng-model="user.gender" value="female" />female<br />
         <input type="button" ng-click="reset()" value="Reset" />
         <input type="submit" ng-click="update(user)" value="Save" />
       </form>
       <pre>form = {{user | json}}</pre>
       <pre>master = {{master | json}}</pre>
    
  
  </div>
</div>

store_management/app/views/welcome/index.html.erb
<div class="sm-site-body">

  <div class="container-fluid sm-site-body">
    
    <div class="row">
      <div class="col-md-12 col-sm-12">
        <!-- header -->
        <div id="sm-header" class="row">
          <!-- Title site -->
          <div class="col-md-6 col-sm-6 sm-logo">
            <!-- Logo (title) -->            
            <p>Store Management</p>
          </div>
            <!-- Main menu -->
          <div class="col-md-6 col-sm-6 sm-index-menu" >
            <ul>
              
              <li class="sm-login"><a href="#"> Sign In </a></li>
              <li><a href="#">About</a></li>
              <li><a href="#products">Product</a></li>
              <li><a href="#">Home</a></li>
            </ul>
          </div> 
        </div>
        <!-- center vertical align content -->
        <div id="sm-content-1" class="row">
          <!-- banner images -->
          <div class="col-md-12 col-sm-12 sm-banner">
                
          </div>
          <!-- concept -->
          <div class="col-md-12 col-sm-12 sm-concept">
                 <h1>Administrador de Inventario y Facturación en un solo sitio</h1>
          </div>
          <!-- sub-concept -->
          <div class="col-md-12 col-sm-12 sm-subconcept">
                 <h3>Administra tu tienda de manera ágil, sencilla y efectiva.</h3>
          </div>
        </div>
        <div class="row"><p class="bg-primary" style="height: 1px"></p></div>
        <div id="products" class="row sm-content-2">
          <div class="col-md-12 col-sm-12">
            <div class="row" style="padding-top: 60px;">
              <div class="col-md-4 col-sm-4" style="text-align: center">
               
                <p ><img src="/assets/admin.jpg" alt="administration" width="200" height="200" class="img-circle"></p>
                <h1>Administración</h1>
                <h3>Dale valor a tu negocio facilitando la administración de tus productos y servicios.</h3>
              </div>
              <div class="col-md-4 col-sm-4" style="text-align: center" >
                <p><img src="/assets/inventory.png" alt="Inventory" width="200" height="200" class="img-circle"></p>
                <h1>Inventario</h1>
                <h3>Mantén tu stock actualizado y entérate a tiempo cuando necesites incrementarlo.</h3>
              </div>
              
              <div class="col-md-4 col-sm-4" style="text-align: center" >
                <p><img src="/assets/factura.jpg" alt="Invoice" width="200" height="200" class="img-circle"></p>
                <h1>Facturación</h1>
                <h3>Genera facturas a tus clientes de manera rápida y eficiente.</h3>
              </div>
            </div>
            
          </div>
        </div>
        <div class="row sm-content-3">
          <div class="col-md-12 col-sm-12">
          </div>
        </div>

        <!-- footer -->
        <div class="row sm-content-4">
          <div class="row" style="padding-bottom: 50px;">
            <div class="col-md-offset-3 col-md-2 col-sm-2">
              <h3 style="color:#00B789">Recursos</h3>
              <p><core-icon icon="chevron-right"></core-icon>Blog</p>
              <p><core-icon icon="chevron-right"></core-icon>Soporte</p>
              <p><core-icon icon="chevron-right"></core-icon>Desarrolladores</p>
            </div>
            <div class="col-md-2 col-sm-2">
              <h3 style="color:#00B789">Comunidad</h3>
              <p><span class="glyphicon glyphicon-pushpin"></span>Twitter</p>
              <p><span class="glyphicon glyphicon-ok"></span>Google+</p>
              <p><core-icon icon="chevron-right"></core-icon>Facebook</p>
            </div>
            <div class="col-md-2 col-sm-2">
              <h3 style="color:#00B789">Contacto</h3>
              <p>efrain.astudillo58@gmail.com</p>
              <p>pittersdb@hotmail.com</p>
              <p>+593 991005371</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 col-sm-12" style="text-align: center;">
              <footer style="color: #BBBBBB">All rigths reserved &copy 2015. Design by Efraín Astudillo</footer>
            </div>
          </div>
        </div>
      </div>   
    </div>
  </div>
</div>



<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Inicio de Sesión</h4>
      </div>
      <div class="modal-body">
        <div class="input-group">
          <span class="input-group-addon" id="sizing-addon1">
            <i class="fa fa-envelope-o fa-fw"></i>
          </span>
          <input type="text" class="form-control" placeholder="Username" aria-describedby="sizing-addon1">
        </div>
        <br />
        <div class="input-group">
          <span class="input-group-addon" id="sizing-addon1">
            <i class="fa fa-key"></i>
          </span>  
          <input type="text" class="form-control" placeholder="Password" aria-describedby="sizing-addon1">
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Login</button>
      </div>
    </div>
  </div>
</div>

store_management/app/views/welcome/login.html.erb
<div id="sm_div_login" layout vertical center center-justified>
  <paper-shadow  z="2"  id="sm_login_definition" layout vertical>

    <%= form_tag( welcome_validate_login_path, method: "post", id: "smFormLogin") do %>
    <div id="name" layout vertical>
      <paper-input-decorator id="smUsername"
        floatinglabel
        label="Usuario"
        validate="^[A-Za-z0-9]*$"
        error="Username should contain only letters or number">
        <input is="core-input">
      </paper-input-decorator>
    
      <paper-input-decorator id="smPassword"
        floatinglabel
        label="Contraseña"
        validate="^[A-Za-z0-9]*$"
        error="Password should contain only letters or number">
        
        <input is="core-input">
      </paper-input-decorator>
    </div>
    
    <div layout horizontal flex>
      <div flex>
        <span><a href="#">Olvidó la clave?.</a></span> <br />
        <span><a href="#">Crear nueva cuenta.</a></span> <br />
        <p id="smMsgLogin"></p>
      </div>
      <div >
        <paper-button id="smLoginButton" raised >
          <core-icon icon="check"></core-icon>
          Login
        </paper-button>
      </div>
    </div>
  
    <div>
      <p>All Rigths Reserved &copy 2015 Develop and Design by Efraín Astudillo</p>
    </div>
    <% end %>
  </paper-shadow>
  
  
</div>